name: GitHub Org Member Manage Action
description: Manage GitHub org memberships in a declarative way.
branding:
  icon: 'at-sign'  
  color: 'green'

# See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs.
inputs:
  gh_token:
    description: >
      A GitHub token with `admin:org` scope.
      This is required to manage organization memberships.
      It is recommended to use a secret to store the token.
    required: true
  members_filepath:
    description: >
      The file path to the YAML file containing the list of members.
      This file will be the single source of truth for the organization's memberships.
    required: false
    default: members.yaml
  dry_run:
    description: >
      If set to `true`, the action will only print the changes that would be made,
      without actually applying them. This is useful for testing and debugging.
    required: false
    default: "false"
  mode:
    description: >
      The mode of operation for the action. There are two modes available: `sync` and `write`.
      - `sync`: This mode synchronizes the organization's memberships with the state defined in the `members_filepath` file. It will add, remove, and update members as needed to match the YAML file.
      - `write`: This mode fetches the current organization memberships and writes them to the `members_filepath` file. This is useful for initializing the a new `members.yaml` file.
    required: false
    default: sync

runs:
  using: docker
  image: Dockerfile
