/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.codingpot.github_org_member_manage_action;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
